services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus

    ports:
      - "127.0.0.1:9090:9090"

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana

    ports:
      - "127.0.0.1:3000:3000"

    volumes:
      - grafana_data:/var/lib/grafana

    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma

    ports:
      - "127.0.0.1:3001:3001"

    volumes:
      - uptime_kuma_data:/app/data

    restart: unless-stopped

volumes:
  grafana_data:
  uptime_kuma_data:
