flowchart TB

    User["👤 Пользователь"]

    Nginx["Nginx<br/>Reverse Proxy"]

    Site["mal-mbv.ru"]

    Grafana["grafana.mal-mbv.ru"]

    Kuma["status.mal-mbv.ru"]

    Docker["Docker Engine"]

    Prometheus["Prometheus"]

    Exporter["Node Exporter"]

    VPS["Ubuntu Server 24.04 LTS"]

    User --> Nginx

    Nginx --> Site
    Nginx --> Grafana
    Nginx --> Kuma

    Grafana --> Prometheus
    Prometheus --> Exporter

    Site -. Static files .-> VPS

    Grafana -. Container .-> Docker
    Prometheus -. Container .-> Docker
    Kuma -. Container .-> Docker

    Exporter -. Installed on host .-> VPS